### ISSUE TITLE
Internal links should be in templating language not hard coded

### ISSUE THREAD

**Issue by falkben** [neurodata/blog.neurodata.io#7]
https://jekyllrb.com/docs/liquid/tags/#linking-to-posts

**Comment by jovo** [comment]
@loftusa can you fix this in the example where i screwed it up, and then show me how.
for some reason, i don't quite understand the syntax (when i tried, i failed).

**Comment by loftusa** [comment]
@jovo fixed in 4dd85bb45e4d3faab740d00638c9280fda3bc531

The date was wrong in the initial link. See https://jekyllrb.com/docs/liquid/tags/#linking-to-posts for documentation on new link style.
